// langs needed de-de,fr-fr,pl-pl,es-es,nl-nl,cz-cz,pt-br,it-it,el-gr,ro-ro

const baseTranslation = { 
	'en-uk': {
		'btn_close': 'Close',
		'btn_submit': 'Submit',
		'btn_reset': 'Reset',
		'btn_reload': 'Reload',
		'btn_fix': 'Fix mismatch',
		'manager_mismatch': 'mismatch',
		'load_template': 'Load template' ,
		'save_template': 'Save as template',
		'command_sent': 'Command sent',
		'no_free_expl': 'No free explorers',
		'no_free_geo': 'No free geologists',
		'not_home' : 'Not your home zone!',
		'bad_template' : 'Bad template file',
		'spec_time_normal': 'Needed time',
		'spec_time_arrival': 'Arrival time',
		'buff_not_recorded' : 'Buff not recorded! Type - ',
		'buff_wrong_zone' : 'wrong zone',
		'buff_wrong_name' : 'name mismatch',
		'buff_not_exist' : 'not exists',
		'buff_buffed' : 'already buffed',
		'buff_not_buffed' : 'not buffed',
		'buff_ready': 'ready',
		'buff_used': 'Buffs will be used:',
		'buff_rec_start': 'Recording started',
		'buff_rec_stop': 'Recording stoped',
		'buff_rec_progress': 'Recording in progress!',
		'buff_zoneowner': 'BuffList ZoneOwner:',
		'buff_not_your_zone': 'This buff list not for your zone!',
		'buff_start_record': 'Start recording',
		'buff_stop_record': 'Stop recording',
		'buff_record_more': 'Record more',
		'buff_welcome': 'Welcome to buff manager!',
		'buff_welcome_block': '<p>You can record what you need to buff and then replay it automatically. Press "Start recording" button and buff your (or friend) buildings. After that come back and press "Stop recording". You will see list of buildings and its buffs. Save it as temlate and next time just load template and press Submit.</p><p>Buildings with red background will not be buffed.. also if one of available buff rows be red not all buildings with this buff will be buffed</p>',
		'experimental': "EXPERIMENTAL",
		'auc_warning': 'Use only after pay 10k gold in unity. Always reload data before making bid.',
		'auc_current': "Current auctionId:",
		'auc_bidding_count': "Bidding count:",
		'auc_endtime': "End time:",
		'auc_ended': "ended",
		'auc_item': "Auction item:",
		'auc_item_desc': "Item description:",
		'auc_initial_cost': "Initial cost:",
		'auc_increment': "Inrement by:",
		'auc_bid_for': "Place bet for:",
		'auc_you_have': "You have:",
		'auc_your_max': "Your bet is max, so you cant place another bet",
		'auc_do_bid': 'Place bid'
	},
	'en-us': {
		'btn_close': 'Close',
		'btn_submit': 'Submit',
		'btn_reset': 'Reset',
		'btn_reload': 'Reload',
		'btn_fix': 'Fix mismatch',
		'manager_mismatch': 'mismatch',
		'load_template': 'Load template' ,
		'save_template': 'Save as template',
		'command_sent': 'Command sent',
		'no_free_expl': 'No free explorers',
		'no_free_geo': 'No free geologists',
		'not_home' : 'Not your home zone!',
		'bad_template' : 'Bad template file',
		'spec_time_normal': 'Needed time',
		'spec_time_arrival': 'Arrival time',
		'buff_not_recorded' : 'Buff not recorded! Type - ',
		'buff_wrong_zone' : 'wrong zone',
		'buff_wrong_name' : 'name mismatch',
		'buff_not_exist' : 'not exists',
		'buff_buffed' : 'already buffed',
		'buff_not_buffed' : 'not buffed',
		'buff_ready': 'ready',
		'buff_used': 'Buffs will be used:',
		'buff_rec_start': 'Recording started',
		'buff_rec_stop': 'Recording stoped',
		'buff_rec_progress': 'Recording in progress!',
		'buff_zoneowner': 'BuffList ZoneOwner:',
		'buff_not_your_zone': 'This buff list not for your zone!',
		'buff_start_record': 'Start recording',
		'buff_stop_record': 'Stop recording',
		'buff_record_more': 'Record more',
		'buff_welcome': 'Welcome to buff manager!',
		'buff_welcome_block': '<p>You can record what you need to buff and then replay it automatically. Press "Start recording" button and buff your (or friend) buildings. After that come back and press "Stop recording". You will see list of buildings and its buffs. Save it as temlate and next time just load template and press Submit.</p><p>Buildings with red background will not be buffed.. also if one of available buff rows be red not all buildings with this buff will be buffed</p>',
		'experimental': "EXPERIMENTAL",
		'auc_warning': 'Use only after pay 10k gold in unity. Always reload data before making bid.',
		'auc_current': "Current auctionId:",
		'auc_bidding_count': "Bidding count:",
		'auc_endtime': "End time:",
		'auc_ended': "ended",
		'auc_item': "Auction item:",
		'auc_item_desc': "Item description:",
		'auc_initial_cost': "Initial cost:",
		'auc_increment': "Inrement by:",
		'auc_bid_for': "Place bet for:",
		'auc_you_have': "You have:",
		'auc_your_max': "Your bet is max, so you cant place another bet",
		'auc_do_bid': 'Place bid'
	},
	'ru-ru': {
		'btn_close': 'Закрыть',
		'btn_submit': 'Отправить',
		'btn_reset': 'Сбросить',
		'btn_reload': 'Обновить',
		'btn_fix': 'Исправить',
		'manager_mismatch': 'отличается',
		'load_template': 'Загрузить шаблон' ,
		'save_template': 'Сохранить как шаблон',
		'command_sent': 'Команда отправлена',
		'no_free_expl': 'Нет свободных исследователей',
		'no_free_geo': 'Нет свободных геологов',
		'not_home' : 'Это не ваша домашняя зона!',
		'bad_template' : 'Неправильный или поврежденный файл шаблона',
		'spec_time_normal': 'Требуемое время',
		'spec_time_arrival': 'Время возвращения',
		'buff_not_recorded' : 'Баф не записан! Тип - ',
		'buff_wrong_zone' : 'не та зона',
		'buff_wrong_name' : 'имя не совпадает',
		'buff_not_exist' : 'не существует',
		'buff_buffed' : 'уже бафнуто',
		'buff_not_buffed' : 'не бафнуто',
		'buff_ready': 'готов',
		'buff_used': 'Будут использованы бафы:',
		'buff_rec_start': 'Запись начата',
		'buff_rec_stop': 'Запись остановлена',
		'buff_rec_progress': 'Идёт запись!',
		'buff_zoneowner': 'Список бафов для зоны игрока:',
		'buff_not_your_zone': 'Этот список бафов не для вашей зоны!',
		'buff_start_record': 'Начать запись',
		'buff_stop_record': 'Остановить запись',
		'buff_record_more': 'Записать еще',
		'buff_welcome': 'Добро пожаловать в менеджер бафов!',
		'buff_welcome_block': '<p>Вы можете записать бафы нужных зданий, чтобы потом бафать их в автоматическом режиме. Нажмите "Начать запись" и бафйате свои или дружеские здания. После окончания вернитесь сюда и нажмите кнопку "Остановить запись". Вы увидите список зданий и бафов. Сохраните его как шаблон. В следующий раз загрузите шаблон, проверьте список и нажмите "Отправить".</p><p>Здания со статусом, отличным от "готов" не будут бафнуты. Если у вас не хватает бафов на все здания, то часть не будет бафнута.</p>',
		'experimental': "ЭКСПЕРИМЕНТАЛЬНАЯ ФУНКЦИЯ!",
		'auc_warning': 'Используйте только после разблокировки аукциона за 10 000 монет в Юнити.',
		'auc_current': "Текущий ID аукциона:",
		'auc_bidding_count': "Сделано ставок:",
		'auc_endtime': "До окончания:",
		'auc_ended': "Аукцион закончен",
		'auc_item': "Лот аукциона:",
		'auc_item_desc': "Описание лота:",
		'auc_initial_cost': "Начальная цена:",
		'auc_increment': "Увеличение цены за каждую ставку:",
		'auc_bid_for': "Разместить ставку за:",
		'auc_you_have': "У вас есть:",
		'auc_your_max': "Ваша ставка максимальная, нельзя сделать ставку",
		'auc_do_bid': 'Сделать ставку'
	},
	"pl-pl": {
      "btn_close":"Zamknij",
      "btn_submit":"Wyślij",
      "btn_reset":"Resetuj",
      "btn_reload":"Przeładuj",
      "btn_fix":"Napraw niedopasowanie",
      "manager_mismatch":"Niedopasowanie",
      "load_template":"Wczytaj szablon",
      "save_template":"Zapisz jako szablon",
      "command_sent":"Komenda wysłana",
      "no_free_expl":"Brak wolnych odkrywców",
      "no_free_geo":"Brak wolnych geologów",
      "not_home":"Nie twoja strefa domowa!",
      "bad_template":"Niepoprawny plik szablonu",
      "spec_time_normal":"Potrzebny czas",
      "spec_time_arrival":"Czas powrotu",
      "buff_not_recorded":"Premia nie jest zarejestrowana! Typ - ",
      "buff_wrong_zone":"Niewłaściwa strefa premii",
      "buff_wrong_name":"Niedopasowanie nazwy premii",
      "buff_not_exist":"Premia nie istnieje",
      "buff_buffed":"Premia już przydzielona",
      "buff_not_buffed":"Premia nie przydzielona",
      "buff_ready":"Premia gotowa",
      "buff_used":"Użyte premie:",
      "buff_rec_start":"Rozpocznij nagrywanie",
      "buff_rec_stop":"Zatrzymaj nagrywanie",
      "buff_rec_progress":"Nagrywanie premii w toku!",
      "buff_zoneowner":"Właściciel premiowanej strefy:",
      "buff_not_your_zone":"Ta lista premii nie jest przeznaczona dla Twojej strefy!",
      "buff_start_record":"Rozpocznij nagrywanie",
      "buff_stop_record":"Zatrzymaj nagrywanie",
      "buff_record_more":"Nagraj więcej premii",
      "buff_welcome":"Witamy w menadżerze premii!",
      "buff_welcome_block":'<p>Możesz nagrać premie budynków, a następnie automatycznie to odtworzyć. Naciśnij przycisk "Rozpocznij nagrywanie" i premiuj swoje (lub znajomego) budynki. Po tym, wróć i naciśnij "Zatrzymaj nagrywanie". Zobaczysz listę budynków i ich premii. Zapisz to jako szablon i następnym razem, po prostu załaduj szablon i wciśnij Wyślij.</p><p>Budynki z czerwonym tłem nie będą premiowane... także, jeśli jedna z dostępnych zakładek premii będzie czerwona, nie wszystkie budynki będą premiowane</p>',
      "experimental":"EXPERYMENTALNE",
      "auc_warning":"Użyj tylko po zapłaceniu 10ooo monet w Unity. Zawsze przeładuj zanim dokonasz oferty.",
      "auc_current":"Aktualna aukcja:",
      "auc_bidding_count":"Licznik ofert:",
      "auc_endtime":"Czas zakończenia:",
      "auc_ended":"Zakończono",
      "auc_item":"Przedmiot aukcji:",
      "auc_item_desc":"Opis przedmiotu:",
      "auc_initial_cost":"Koszt początkowy:",
      "auc_increment":"Przyrost:",
      "auc_bid_for":"Postaw zakład na:",
      "auc_you_have":"Posiadasz:",
      "auc_your_max":"Twój zakład jest maksymalny, więc nie możesz postawić kolejnego zakładu",
      "auc_do_bid":"Złóż ofertę"
   }
};
