// langs needed de-de,fr-fr,pl-pl,es-es,nl-nl,cz-cz,pt-br,it-it,el-gr,ro-ro

const baseTranslation = { 
	'en-uk': {
		'btn_close': 'Close',
		'btn_submit': 'Submit',
		'btn_reset': 'Reset',
		'btn_reload': 'Reload',
		'btn_fix': 'Fix mismatch',
		'manager_mismatch': 'mismatch',
		'load_template': 'Load template' ,
		'save_template': 'Save as template',
		'command_sent': 'Command sent',
		'no_free_expl': 'No free explorers',
		'no_free_geo': 'No free geologists',
		'not_home' : 'Not your home zone!',
		'bad_template' : 'Bad template file',
		'spec_time_normal': 'Needed time',
		'spec_time_arrival': 'Arrival time',
		'buff_not_recorded' : 'Buff not recorded! Type - ',
		'buff_wrong_zone' : 'wrong zone',
		'buff_wrong_name' : 'name mismatch',
		'buff_not_exist' : 'not exists',
		'buff_buffed' : 'already buffed',
		'buff_not_buffed' : 'not buffed',
		'buff_ready': 'ready',
		'buff_used': 'Buffs that will be used:',
		'buff_rec_start': 'Recording started',
		'buff_rec_stop': 'Recording stopped',
		'buff_rec_progress': 'Recording in progress!',
		'buff_zoneowner': 'BuffList ZoneOwner:',
		'buff_not_your_zone': 'This buff list is not for your zone!',
		'buff_start_record': 'Start recording',
		'buff_stop_record': 'Stop recording',
		'buff_record_more': 'Record more',
		'buff_welcome': 'Welcome to buff manager!',
		'buff_welcome_block': '<p>You can record what you need to buff and then replay it automatically. Press "Start recording" button and buff your (or friend) buildings. After that come back and press "Stop recording". You will see list of buildings and its buffs. Save it as a template and next time just load template and press Submit.</p><p>Buildings with red background will not be buffed.. Also, if one of the available buffs rows is red, not all buildings will be buffed with this buff.</p>',
		'experimental': "EXPERIMENTAL",
		'auc_warning': 'Use only after paying 10k gold in unity. Always reload data before making bid.',
		'auc_current': "Current auctionId:",
		'auc_bidding_count': "Bidding count:",
		'auc_endtime': "End time:",
		'auc_ended': "ended",
		'auc_item': "Auction item:",
		'auc_item_desc': "Item description:",
		'auc_initial_cost': "Initial cost:",
		'auc_increment': "Inrement by:",
		'auc_bid_for': "Place bet for:",
		'auc_you_have': "You have:",
		'auc_your_max': "You are the highest bidder, so you can't place another bet",
		'auc_do_bid': 'Place bid'
	},
	'en-us': {
		'btn_close': 'Close',
		'btn_submit': 'Submit',
		'btn_reset': 'Reset',
		'btn_reload': 'Reload',
		'btn_fix': 'Fix mismatch',
		'manager_mismatch': 'mismatch',
		'load_template': 'Load template' ,
		'save_template': 'Save as template',
		'command_sent': 'Command sent',
		'no_free_expl': 'No free explorers',
		'no_free_geo': 'No free geologists',
		'not_home' : 'Not your home zone!',
		'bad_template' : 'Bad template file',
		'spec_time_normal': 'Needed time',
		'spec_time_arrival': 'Arrival time',
		'buff_not_recorded' : 'Buff not recorded! Type - ',
		'buff_wrong_zone' : 'wrong zone',
		'buff_wrong_name' : 'name mismatch',
		'buff_not_exist' : 'not exists',
		'buff_buffed' : 'already buffed',
		'buff_not_buffed' : 'not buffed',
		'buff_ready': 'ready',
		'buff_used': 'Buffs will be used:',
		'buff_rec_start': 'Recording started',
		'buff_rec_stop': 'Recording stopped',
		'buff_rec_progress': 'Recording in progress!',
		'buff_zoneowner': 'BuffList ZoneOwner:',
		'buff_not_your_zone': 'This buff list not for your zone!',
		'buff_start_record': 'Start recording',
		'buff_stop_record': 'Stop recording',
		'buff_record_more': 'Record more',
		'buff_welcome': 'Welcome to buff manager!',
		'buff_welcome_block': '<p>You can record what you need to buff and then replay it automatically. Press "Start recording" button and buff your (or friend) buildings. After that come back and press "Stop recording". You will see list of buildings and its buffs. Save it as a template and next time just load template and press Submit.</p><p>Buildings with red background will not be buffed.. Also, if one of the available buffs rows is red, not all buildings will be buffed with this buff.</p>',
		'experimental': "EXPERIMENTAL",
		'auc_warning': 'Use only after paying 10k gold in unity. Always reload data before making bid.',
		'auc_current': "Current auctionId:",
		'auc_bidding_count': "Bidding count:",
		'auc_endtime': "End time:",
		'auc_ended': "ended",
		'auc_item': "Auction item:",
		'auc_item_desc': "Item description:",
		'auc_initial_cost': "Initial cost:",
		'auc_increment': "Inrement by:",
		'auc_bid_for': "Place bet for:",
		'auc_you_have': "You have:",
		'auc_your_max': "You are the highest bidder, so you can't place another bet",
		'auc_do_bid': 'Place bid'
	},
	'ru-ru': {
		'btn_close': 'Закрыть',
		'btn_submit': 'Отправить',
		'btn_reset': 'Сбросить',
		'btn_reload': 'Обновить',
		'btn_fix': 'Исправить',
		'manager_mismatch': 'отличается',
		'load_template': 'Загрузить шаблон' ,
		'save_template': 'Сохранить как шаблон',
		'command_sent': 'Команда отправлена',
		'no_free_expl': 'Нет свободных исследователей',
		'no_free_geo': 'Нет свободных геологов',
		'not_home' : 'Это не ваша домашняя зона!',
		'bad_template' : 'Неправильный или поврежденный файл шаблона',
		'spec_time_normal': 'Требуемое время',
		'spec_time_arrival': 'Время возвращения',
		'buff_not_recorded' : 'Баф не записан! Тип - ',
		'buff_wrong_zone' : 'не та зона',
		'buff_wrong_name' : 'имя не совпадает',
		'buff_not_exist' : 'не существует',
		'buff_buffed' : 'уже бафнуто',
		'buff_not_buffed' : 'не бафнуто',
		'buff_ready': 'готов',
		'buff_used': 'Будут использованы бафы:',
		'buff_rec_start': 'Запись начата',
		'buff_rec_stop': 'Запись остановлена',
		'buff_rec_progress': 'Идёт запись!',
		'buff_zoneowner': 'Список бафов для зона игрока:',
		'buff_not_your_zone': 'Этот список бафов не для вашей зоны!',
		'buff_start_record': 'Начать запись',
		'buff_stop_record': 'Остановить запись',
		'buff_record_more': 'Записать еще',
		'buff_welcome': 'Добро пожаловать в менеджер бафов!',
		'buff_welcome_block': '<p>Вы можете записать то что вам нужно бафнуть и потом делать это в автоматическом режиме. Нажмите "Начать запись" и бафате свои или дружеские здания. После этого вернитесь сюда и нажмите кнопку "Остановить запись". Вы увидите список зданий и бафов.. Сохраните его как шаблон, и в следующий раз загрузите шаблон, проверьте список и нажмите "Отправить".</p><p>Здания с статусом отличным от "готов" не будут бафнуты. Если у вас не хватает бафов на все здания то часть не будет бафнута.</p>',
		'experimental': "ЭКСПЕРИМЕНТАЛЬНАЯ ФУНКЦИЯ!",
		'auc_warning': 'Используйте только после разблокировки аукциона за 10 000 монет в юнити.',
		'auc_current': "Текущий ID аукциона:",
		'auc_bidding_count': "Сделано ставок:",
		'auc_endtime': "До окончания:",
		'auc_ended': "аукцион закончен",
		'auc_item': "Лот аукциона:",
		'auc_item_desc': "Описание лота:",
		'auc_initial_cost': "Начальная цена:",
		'auc_increment': "Увеличение цены за каждую ставку:",
		'auc_bid_for': "Разместить ставку за:",
		'auc_you_have': "У вас есть:",
		'auc_your_max': "Ваша ставка максимальная, нельзя сделать ставку",
		'auc_do_bid': 'Сделать ставку'
	},
	'es-es': {
		'btn_close': 'Cerrar',
		'btn_submit': 'Enviar',
		'btn_reset': 'Reiniciar',
		'btn_reload': 'Recargar',
		'btn_fix': 'Corregir diferencia(s)',
		'manager_mismatch': 'Diferente',
		'load_template': 'Cargar plantilla' ,
		'save_template': 'Guardar plantilla',
		'command_sent': 'Comando enviado',
		'no_free_expl': 'No tienes exploradores disponibles',
		'no_free_geo': 'No tienes geólogos disponibles',
		'not_home' : '¡Esta no es tu isla!',
		'bad_template' : 'Mala plantilla',
		'spec_time_normal': 'Duración de búsqueda',
		'spec_time_arrival': 'Hora de llegada',
		'buff_not_recorded' : '¡Potenciador no registrado! Tipo - ',
		'buff_wrong_zone' : 'Zona incorrecta',
		'buff_wrong_name' : 'Edificio distinto',
		'buff_not_exist' : 'No existe',
		'buff_buffed' : 'Ya potenciado',
		'buff_not_buffed' : 'No potenciado',
		'buff_ready': 'Listo',
		'buff_used': 'Potenciadores que serán utilizados:',
		'buff_rec_start': 'Grabación iniciada',
		'buff_rec_stop': 'Grabación detenida',
		'buff_rec_progress': '¡Grabación en curso!',
		'buff_zoneowner': 'Propietario de la zona a potenciar:',
		'buff_not_your_zone': '¡Esta plantilla no es para esta zona!',
		'buff_start_record': 'Iniciar grabación',
		'buff_stop_record': 'Detener grabación',
		'buff_record_more': 'Grabar más',
		'buff_welcome': '¡Bienvenido al gestor de potenciadoree!',
		'buff_welcome_block': '<p>Puedes grabar lo que necesitas potenciar y luego reproducirlo automáticamente. Presiona el botón "Iniciar grabación" y potencia tus edificios (o los de tus amigos). Después, regresa y presiona "Detener grabación". Verás una lista de edificios y sus potenciadores. Guárdalo como plantilla y la próxima vez simplemente carga la plantilla y presiona Enviar.</p><p>Los edificios en rojo no se potenciarán. Además, si uno de los potenciadores de la plantilla está en rojo (es decir, no tienes suficientes), no se potenciarán todos los edificios asignados con este potenciador.</p>',
		'experimental': "EXPERIMENTAL",
		'auc_warning': 'Usar solo después de desbloquear por 10k de oro en Unity (navegador). Recarga siempre antes de pujar.',
		'auc_current': "Mejor postorId:",
		'auc_bidding_count': "Recuento de pujas:",
		'auc_endtime': "Hora de fin:",
		'auc_ended': "Finalizada",
		'auc_item': "Artículo subastado:",
		'auc_item_desc': "Descripción del artículo:",
		'auc_initial_cost': "Puja inicial:",
		'auc_increment': "Incrementos de:",
		'auc_bid_for': "Puja por:",
		'auc_you_have': "Tienes:",
		'auc_your_max': "Eres el mejor postor, no puedes pujar de nuevo",
		'auc_do_bid': 'Pujar'
	}
};
